# Navigation Links
#   To link a homepage section, specify the URL as a hash `#` followed by the
#     `id` of the desired block in `content/_index.md`.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: '#about'
    weight: 10
  - name: Experience
    url: '#experience'
    weight: 20
  - name: Publications
    url: /publication/
    weight: 30
  - name: Talks
    url: '#talks'
    weight: 40
  - name: Awards
    url: '#awards'
    weight: 50
  - name: CV
    url: /cv/
    weight: 60
